title: Replicate THIS!
description: How many tutorials/analyses out there I can *actually* replicate? Let's drive progress with clear communication, open code, and shared data.


url: https://kelsiwest-binf.github.io/
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: About
      url: /about
    - title: Contact
      url: https://kelsi-west.webflow.io/#west-contact
    - title: Wild West Home
      url: https://kelsi-west.webflow.io/

social:
    github: kelsiwest-binf
    twitter: West_KelsiO
    email: kelsi.west979@[google's mail service]
    linkedin: kelsiwest-binf

#oogle_analytics: "UA-58263416-1"

#disqus:
    #shortname: brianmaierjr
